import { GroupOffer } from '../types/groupOffer';

/**
 * Servicio para manejar las operaciones relacionadas con ofertas de grupos
 */

/**
 * Obtiene todas las ofertas de grupos disponibles
 * @returns Promise con el listado de ofertas
 */
export const fetchGroupOffers = async (): Promise<GroupOffer[]> => {
  // TODO: Implementar llamada al API del backend
  // Ejemplo: const response = await fetch('/api/group-offers');
  // return response.json();
  
  // Datos de prueba temporal
  return [
    {
      id: '1',
      title: 'Grupo Algoritmos y Estructuras de Datos',
      description: 'Buscamos compañeros para formar grupo de estudio para la materia. Nos reunimos los martes y jueves.',
      subject: 'Algoritmos y Estructuras de Datos',
      cathedra: 'Wachenchauzer',
      semester: '1C 2025',
      totalSlots: 4,
      availableSlots: 2,
      author: {
        id: 'user1',
        name: 'Juan Pérez',
        profileUrl: '/profile/user1',
      },
      createdAt: '2025-11-01T10:00:00Z',
      updatedAt: '2025-11-01T10:00:00Z',
    },
    {
      id: '2',
      title: 'Trabajo Práctico - Base de Datos',
      description: 'Necesitamos un integrante más para completar el equipo del TP final.',
      subject: 'Base de Datos',
      cathedra: 'Servetto',
      semester: '1C 2025',
      totalSlots: 3,
      availableSlots: 1,
      author: {
        id: 'user2',
        name: 'María González',
        profileUrl: '/profile/user2',
      },
      createdAt: '2025-11-05T14:30:00Z',
      updatedAt: '2025-11-05T14:30:00Z',
    },
    {
      id: '3',
      title: 'Grupo de Estudio - Análisis Matemático II',
      description: 'Grupo para estudiar y resolver guías de práctica. Buscamos gente comprometida.',
      subject: 'Análisis Matemático II',
      cathedra: 'Massey',
      semester: '2C 2024',
      totalSlots: 5,
      availableSlots: 3,
      author: {
        id: 'user3',
        name: 'Carlos Rodríguez',
        profileUrl: '/profile/user3',
      },
      createdAt: '2025-11-08T09:15:00Z',
      updatedAt: '2025-11-08T09:15:00Z',
    },
    {
      id: '4',
      title: 'TP Final - Algoritmos Avanzados',
      description: 'Buscamos 1 persona más para completar grupo del TP integrador.',
      subject: 'Algoritmos y Estructuras de Datos',
      cathedra: 'Méndez',
      semester: '1C 2025',
      totalSlots: 4,
      availableSlots: 1,
      author: {
        id: 'user4',
        name: 'Ana Martínez',
        profileUrl: '/profile/user4',
      },
      createdAt: '2025-11-09T11:00:00Z',
      updatedAt: '2025-11-09T11:00:00Z',
    },
    {
      id: '5',
      title: 'Grupo SQL y NoSQL',
      description: 'Estudiamos juntos para el parcial. Nos juntamos presencial en el campus.',
      subject: 'Base de Datos',
      cathedra: 'Carnuccio',
      semester: '2C 2024',
      totalSlots: 3,
      availableSlots: 2,
      author: {
        id: 'user5',
        name: 'Pedro Fernández',
        profileUrl: '/profile/user5',
      },
      createdAt: '2025-11-10T08:30:00Z',
      updatedAt: '2025-11-10T08:30:00Z',
    },
    {
      id: '6',
      title: 'Proyecto Integrador - Física I',
      description: 'Armamos grupo para el proyecto final. Ya tenemos 2 miembros, nos falta 1 más.',
      subject: 'Física I',
      cathedra: 'Schmiegelow',
      semester: '1C 2025',
      totalSlots: 3,
      availableSlots: 1,
      author: {
        id: 'user6',
        name: 'Laura Sánchez',
        profileUrl: '/profile/user6',
      },
      createdAt: '2025-11-11T15:00:00Z',
      updatedAt: '2025-11-11T15:00:00Z',
    },
    {
      id: '7',
      title: 'Laboratorio de Física - Sesiones Prácticas',
      description: 'Grupo para hacer juntos los informes de laboratorio. Nos juntamos después de cada práctica.',
      subject: 'Física I',
      cathedra: 'Tirao',
      semester: '2C 2024',
      totalSlots: 4,
      availableSlots: 2,
      author: {
        id: 'user7',
        name: 'Roberto Díaz',
        profileUrl: '/profile/user7',
      },
      createdAt: '2025-11-12T10:30:00Z',
      updatedAt: '2025-11-12T10:30:00Z',
    },
    {
      id: '8',
      title: 'Resolución de Parciales Viejos - Análisis II',
      description: 'Nos juntamos sábados por la tarde para resolver parciales anteriores y despejar dudas.',
      subject: 'Análisis Matemático II',
      cathedra: 'Massey',
      semester: '1C 2025',
      totalSlots: 5,
      availableSlots: 1,
      author: {
        id: 'user8',
        name: 'Sofia Morales',
        profileUrl: '/profile/user8',
      },
      createdAt: '2025-11-13T14:00:00Z',
      updatedAt: '2025-11-13T14:00:00Z',
    },
    {
      id: '9',
      title: 'TP de Árboles y Grafos',
      description: 'Necesitamos completar el grupo para el trabajo práctico de estructuras avanzadas.',
      subject: 'Algoritmos y Estructuras de Datos',
      cathedra: 'Wachenchauzer',
      semester: '2C 2024',
      totalSlots: 4,
      availableSlots: 2,
      author: {
        id: 'user9',
        name: 'Diego Torres',
        profileUrl: '/profile/user9',
      },
      createdAt: '2025-11-14T09:00:00Z',
      updatedAt: '2025-11-14T09:00:00Z',
    },
    {
      id: '10',
      title: 'Grupo de Apoyo - Sistemas Operativos',
      description: 'Estudiamos juntos para la materia. Nivel principiante, explicamos con paciencia.',
      subject: 'Sistemas Operativos',
      cathedra: 'Venere',
      semester: '1C 2025',
      totalSlots: 6,
      availableSlots: 4,
      author: {
        id: 'user10',
        name: 'Camila López',
        profileUrl: '/profile/user10',
      },
      createdAt: '2025-11-15T11:30:00Z',
      updatedAt: '2025-11-15T11:30:00Z',
    },
    {
      id: '11',
      title: 'Proyecto Shell en C - Sistemas Operativos',
      description: 'Buscamos un programador más para el proyecto final de la materia. Experiencia en C requerida.',
      subject: 'Sistemas Operativos',
      cathedra: 'Becher',
      semester: '2C 2024',
      totalSlots: 3,
      availableSlots: 1,
      author: {
        id: 'user11',
        name: 'Martín Ruiz',
        profileUrl: '/profile/user11',
      },
      createdAt: '2025-11-16T13:00:00Z',
      updatedAt: '2025-11-16T13:00:00Z',
    },
    {
      id: '12',
      title: 'Diseño de Base de Datos - Proyecto E-Commerce',
      description: 'TP integrador sobre diseño y normalización. Buscamos gente con ganas de aprender.',
      subject: 'Base de Datos',
      cathedra: 'Servetto',
      semester: '1C 2025',
      totalSlots: 4,
      availableSlots: 3,
      author: {
        id: 'user12',
        name: 'Valentina Castro',
        profileUrl: '/profile/user12',
      },
      createdAt: '2025-11-17T16:00:00Z',
      updatedAt: '2025-11-17T16:00:00Z',
    },
    {
      id: '13',
      title: 'Preparación Segundo Parcial - Física I',
      description: 'Grupo intensivo para preparar el segundo parcial. Nos enfocamos en cinemática y dinámica.',
      subject: 'Física I',
      cathedra: 'Schmiegelow',
      semester: '1C 2025',
      totalSlots: 4,
      availableSlots: 0,
      author: {
        id: 'user13',
        name: 'Lucas Herrera',
        profileUrl: '/profile/user13',
      },
      createdAt: '2025-11-18T08:00:00Z',
      updatedAt: '2025-11-18T08:00:00Z',
    },
    {
      id: '14',
      title: 'Series y Sucesiones - Análisis II',
      description: 'Nos juntamos para practicar series de Fourier y convergencia. Virtual por Meet.',
      subject: 'Análisis Matemático II',
      cathedra: 'Massey',
      semester: '2C 2024',
      totalSlots: 5,
      availableSlots: 2,
      author: {
        id: 'user14',
        name: 'Florencia Vega',
        profileUrl: '/profile/user14',
      },
      createdAt: '2025-11-19T17:30:00Z',
      updatedAt: '2025-11-19T17:30:00Z',
    },
    {
      id: '15',
      title: 'Threading y Concurrencia - Sistemas Operativos',
      description: 'Grupo para resolver TPs de procesos, threads y sincronización. Nivel avanzado.',
      subject: 'Sistemas Operativos',
      cathedra: 'Venere',
      semester: '1C 2025',
      totalSlots: 3,
      availableSlots: 1,
      author: {
        id: 'user15',
        name: 'Joaquín Méndez',
        profileUrl: '/profile/user15',
      },
      createdAt: '2025-11-20T12:00:00Z',
      updatedAt: '2025-11-20T12:00:00Z',
    },
    {
      id: '16',
      title: 'Heap Sort y Quick Sort - Algoritmos',
      description: 'Practicamos algoritmos de ordenamiento avanzados. Implementamos desde cero.',
      subject: 'Algoritmos y Estructuras de Datos',
      cathedra: 'Méndez',
      semester: '2C 2024',
      totalSlots: 4,
      availableSlots: 3,
      author: {
        id: 'user16',
        name: 'Patricia Gómez',
        profileUrl: '/profile/user16',
      },
      createdAt: '2025-11-21T10:00:00Z',
      updatedAt: '2025-11-21T10:00:00Z',
    },
    {
      id: '17',
      title: 'Análisis de Complejidad Algorítmica',
      description: 'Nos enfocamos en Big O, notación asintótica y análisis de performance.',
      subject: 'Algoritmos y Estructuras de Datos',
      cathedra: 'Wachenchauzer',
      semester: '1C 2025',
      totalSlots: 5,
      availableSlots: 2,
      author: {
        id: 'user17',
        name: 'Esteban Vargas',
        profileUrl: '/profile/user17',
      },
      createdAt: '2025-11-22T14:30:00Z',
      updatedAt: '2025-11-22T14:30:00Z',
    },
    {
      id: '18',
      title: 'Backtracking y Programación Dinámica',
      description: 'Resolvemos problemas clásicos: mochila, cambio de monedas, caminos mínimos.',
      subject: 'Algoritmos y Estructuras de Datos',
      cathedra: 'Méndez',
      semester: '1C 2025',
      totalSlots: 3,
      availableSlots: 1,
      author: {
        id: 'user18',
        name: 'Gabriela Ramos',
        profileUrl: '/profile/user18',
      },
      createdAt: '2025-11-23T16:00:00Z',
      updatedAt: '2025-11-23T16:00:00Z',
    },
    {
      id: '19',
      title: 'Transacciones y ACID - Base de Datos',
      description: 'Estudiamos propiedades ACID, niveles de aislamiento y manejo de transacciones.',
      subject: 'Base de Datos',
      cathedra: 'Carnuccio',
      semester: '2C 2024',
      totalSlots: 4,
      availableSlots: 2,
      author: {
        id: 'user19',
        name: 'Fernando Silva',
        profileUrl: '/profile/user19',
      },
      createdAt: '2025-11-24T09:30:00Z',
      updatedAt: '2025-11-24T09:30:00Z',
    },
    {
      id: '20',
      title: 'Optimización de Queries SQL',
      description: 'Aprendemos a usar EXPLAIN, índices y cómo mejorar el performance de consultas.',
      subject: 'Base de Datos',
      cathedra: 'Servetto',
      semester: '1C 2025',
      totalSlots: 5,
      availableSlots: 4,
      author: {
        id: 'user20',
        name: 'Adriana Ortiz',
        profileUrl: '/profile/user20',
      },
      createdAt: '2025-11-25T11:00:00Z',
      updatedAt: '2025-11-25T11:00:00Z',
    },
    {
      id: '21',
      title: 'MongoDB y Bases NoSQL',
      description: 'Exploramos bases de datos NoSQL. Proyecto práctico con MongoDB y Express.',
      subject: 'Base de Datos',
      cathedra: 'Carnuccio',
      semester: '1C 2025',
      totalSlots: 4,
      availableSlots: 1,
      author: {
        id: 'user21',
        name: 'Ricardo Medina',
        profileUrl: '/profile/user21',
      },
      createdAt: '2025-11-26T15:30:00Z',
      updatedAt: '2025-11-26T15:30:00Z',
    },
    {
      id: '22',
      title: 'Integrales Múltiples - Análisis II',
      description: 'Resolvemos integrales dobles y triples. Cambios de coordenadas.',
      subject: 'Análisis Matemático II',
      cathedra: 'Massey',
      semester: '1C 2025',
      totalSlots: 4,
      availableSlots: 3,
      author: {
        id: 'user22',
        name: 'Cecilia Navarro',
        profileUrl: '/profile/user22',
      },
      createdAt: '2025-11-27T13:00:00Z',
      updatedAt: '2025-11-27T13:00:00Z',
    },
    {
      id: '23',
      title: 'Ecuaciones Diferenciales Ordinarias',
      description: 'Grupo avanzado para EDOs de primer y segundo orden. Aplicaciones físicas.',
      subject: 'Análisis Matemático II',
      cathedra: 'Massey',
      semester: '2C 2024',
      totalSlots: 3,
      availableSlots: 0,
      author: {
        id: 'user23',
        name: 'Manuel Rojas',
        profileUrl: '/profile/user23',
      },
      createdAt: '2025-11-28T10:30:00Z',
      updatedAt: '2025-11-28T10:30:00Z',
    },
    {
      id: '24',
      title: 'Cálculo Vectorial y Campos',
      description: 'Gradiente, divergencia, rotacional y teoremas integrales.',
      subject: 'Análisis Matemático II',
      cathedra: 'Massey',
      semester: '1C 2025',
      totalSlots: 5,
      availableSlots: 2,
      author: {
        id: 'user24',
        name: 'Isabel Jiménez',
        profileUrl: '/profile/user24',
      },
      createdAt: '2025-11-29T14:00:00Z',
      updatedAt: '2025-11-29T14:00:00Z',
    },
    {
      id: '25',
      title: 'Mecánica Newtoniana - Física I',
      description: 'Repasamos las tres leyes de Newton y sus aplicaciones prácticas.',
      subject: 'Física I',
      cathedra: 'Tirao',
      semester: '1C 2025',
      totalSlots: 4,
      availableSlots: 1,
      author: {
        id: 'user25',
        name: 'Andrés Paredes',
        profileUrl: '/profile/user25',
      },
      createdAt: '2025-11-30T09:00:00Z',
      updatedAt: '2025-11-30T09:00:00Z',
    },
    {
      id: '26',
      title: 'Trabajo y Energía - Física I',
      description: 'Teorema trabajo-energía, energía potencial y cinética, conservación.',
      subject: 'Física I',
      cathedra: 'Schmiegelow',
      semester: '2C 2024',
      totalSlots: 5,
      availableSlots: 3,
      author: {
        id: 'user26',
        name: 'Daniela Cruz',
        profileUrl: '/profile/user26',
      },
      createdAt: '2025-12-01T11:30:00Z',
      updatedAt: '2025-12-01T11:30:00Z',
    },
    {
      id: '27',
      title: 'Ondas y Oscilaciones - Física I',
      description: 'Estudiamos movimiento armónico simple, ondas mecánicas y acústica.',
      subject: 'Física I',
      cathedra: 'Tirao',
      semester: '2C 2024',
      totalSlots: 4,
      availableSlots: 2,
      author: {
        id: 'user27',
        name: 'Luis Romero',
        profileUrl: '/profile/user27',
      },
      createdAt: '2025-12-02T15:00:00Z',
      updatedAt: '2025-12-02T15:00:00Z',
    },
    {
      id: '28',
      title: 'Deadlocks y Semáforos - Sistemas Operativos',
      description: 'Analizamos condiciones de carrera, deadlocks y técnicas de prevención.',
      subject: 'Sistemas Operativos',
      cathedra: 'Becher',
      semester: '1C 2025',
      totalSlots: 4,
      availableSlots: 3,
      author: {
        id: 'user28',
        name: 'Paula Guzmán',
        profileUrl: '/profile/user28',
      },
      createdAt: '2025-12-03T10:00:00Z',
      updatedAt: '2025-12-03T10:00:00Z',
    },
    {
      id: '29',
      title: 'Gestión de Memoria Virtual',
      description: 'Paginación, segmentación, TLB y algoritmos de reemplazo de páginas.',
      subject: 'Sistemas Operativos',
      cathedra: 'Venere',
      semester: '2C 2024',
      totalSlots: 3,
      availableSlots: 1,
      author: {
        id: 'user29',
        name: 'Sergio Molina',
        profileUrl: '/profile/user29',
      },
      createdAt: '2025-12-04T13:30:00Z',
      updatedAt: '2025-12-04T13:30:00Z',
    },
    {
      id: '30',
      title: 'File Systems y I/O - Sistemas Operativos',
      description: 'Sistemas de archivos, inodos, journaling y manejo de entrada/salida.',
      subject: 'Sistemas Operativos',
      cathedra: 'Becher',
      semester: '1C 2025',
      totalSlots: 5,
      availableSlots: 2,
      author: {
        id: 'user30',
        name: 'Carolina Espinoza',
        profileUrl: '/profile/user30',
      },
      createdAt: '2025-12-05T16:00:00Z',
      updatedAt: '2025-12-05T16:00:00Z',
    },
  ];
};

/**
 * Solicita unirse a una oferta de grupo
 * @param offerId - ID de la oferta a la que se quiere unir
 * @returns Promise con el resultado de la solicitud
 */
export const requestToJoinGroup = async (offerId: string): Promise<void> => {
  // TODO: Implementar llamada al API del backend
  // Ejemplo: await fetch(`/api/group-offers/${offerId}/join`, { method: 'POST' });
  console.log(`Solicitando unirse al grupo: ${offerId}`);
};
